name: passmana
description: A Password Manager Flutter Application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^5.1.0
  fluttericon: ^2.0.0
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  equatable: ^2.0.5
  objectbox: ^2.2.1
  objectbox_flutter_libs: ^2.2.1
  path_provider: ^2.1.0
  url_launcher: ^6.2.3
  path: ^1.8.3
  go_router: ^10.1.0
  cupertino_icons: ^1.0.2
  archive: ^3.6.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  objectbox_generator: ^2.2.1

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - languages/

  fonts:
    - family: Muli
      fonts:
        - asset: fonts/muli/Muli.ttf
        - asset: fonts/muli/Muli-Bold.ttf
        - asset: fonts/muli/Muli-BoldItalic.ttf
        - asset: fonts/muli/Muli-ExtraLight.ttf
        - asset: fonts/muli/Muli-ExtraLightItalic.ttf
        - asset: fonts/muli/Muli-Italic.ttf
        - asset: fonts/muli/Muli-Light.ttf
        - asset: fonts/muli/Muli-LightItalic.ttf
        - asset: fonts/muli/Muli-Semi-BoldItalic.ttf
        - asset: fonts/muli/Muli-SemiBold.ttf