name: passmana
description: A Password Manager Flutter Application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  fluttericon: ^2.0.0
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  equatable: ^2.0.7
  objectbox: ^4.0.3
  objectbox_flutter_libs: ^4.0.3
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  path: ^1.9.0
  go_router: ^14.6.2
  cupertino_icons: ^1.0.8
  archive: ^4.0.2
  file_picker: ^8.1.6
  intl: ^0.19.0
  encrypt:
  flutter_secure_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  objectbox_generator: ^4.0.3
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - languages/

  fonts:
    - family: Muli
      fonts:
        - asset: fonts/muli/Muli.ttf
        - asset: fonts/muli/Muli-Bold.ttf
        - asset: fonts/muli/Muli-BoldItalic.ttf
        - asset: fonts/muli/Muli-ExtraLight.ttf
        - asset: fonts/muli/Muli-ExtraLightItalic.ttf
        - asset: fonts/muli/Muli-Italic.ttf
        - asset: fonts/muli/Muli-Light.ttf
        - asset: fonts/muli/Muli-LightItalic.ttf
        - asset: fonts/muli/Muli-Semi-BoldItalic.ttf
        - asset: fonts/muli/Muli-SemiBold.ttf